### ISSUE TITLE
Failure in creating graph DB  container

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#1]
I'm unable to access the UI in step 1.5 Open OrientDB dashboard
I've been able to deploy other apps in a K8s container, so I'm familiar with the process.

**My data is:**
```
Scotts-MBP:deploy-graph-db-container scottda$ kubectl describe service orientdbservice
Name:			orientdbservice
Namespace:		default
Labels:			service=orientdb
			type=nodeport-service
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"service":"orientdb","type":"nodeport-service"},"name":"orientdbservice","na...
Selector:		service=orientdb,type=container-deployment
Type:			NodePort
IP:			10.10.10.2
Port:			binary	2424/TCP
NodePort:		binary	30720/TCP
Endpoints:		172.30.16.5:2424
Port:			http	2480/TCP
NodePort:		http	30984/TCP
Endpoints:		172.30.16.5:2480
Session Affinity:	None
Events:			<none>
```
```
Scotts-MBP:deploy-graph-db-container scottda$  bx cs workers scottda-cluster1

OK
ID                                                 Public IP       Private IP       Machine Type   State    Status   
kube-dal10-cr31875fc6dfd24e758c2bfc78653c9f7e-w1   169.60.16.76    10.177.184.172   b1c.4x16       normal   Ready   
kube-dal10-cr31875fc6dfd24e758c2bfc78653c9f7e-w2   169.60.16.123   10.177.184.170   b1c.4x16       normal   Ready   
kube-dal10-cr31875fc6dfd24e758c2bfc78653c9f7e-w3   169.60.16.81    10.177.184.174   b1c.4x16       normal   Ready
```

**Instructions are failing here- browser page will not open using:
http://169.60.16.76:30984/studio/index.html
http://169.60.16.123:30984/studio/index.html
http://169.60.16.81:30984/studio/index.html
**

1.5 Open OrientDB dashboard

Get information about the deployed OrientDB service to see which NodePort was assigned for OrientDB's HTTP port 2480.

$ kubectl describe service orientdbservice
Get the public IP address for the worker node in the cluster.

$ bx cs workers mycluster
Open a browser and check out the OrientDB dashboard with the following URL.

http://<IP_address>:<HTTP_NodePort>/studio/index.html

**Comment by shivahr** [comment]
Hi Scott,
Since this issue is related to "Deploying OrientDB container on Bluemix Kubernetes", can you please move this to the project https://github.com/IBM/deploy-graph-db-container (where I have write access and can fix docs/code).

**Comment by scottdangelo** [comment]
I've worked around this by using a different cluster in a different organization. I've had other problems with clusters in "Developer Advocacy", so I don't think it is caused by any issue in this repo's code. I'm closing this issue.
