### ISSUE TITLE
Syntax error in cell 4.2

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#5]
When running the cells as per the instructions, I get the following error after 4.2:

```
 File "<ipython-input-5-99bf9e9f065c>", line 26
    headers2 = {'X-Auth-Token': s_subject_token, 'accept
                                                       ^
SyntaxError: EOL while scanning string literal
```

**Comment by balajikadambi** [comment]
Could you check again with the latest notebook. I did not get the error.

**Comment by balajikadambi** [comment]
The Deploy Orient DB container is a pre-requisite(https://github.com/IBM/deploy-graph-db-container). The credentials for the Orient DB needs to be entered in the notebook.

**Comment by scottdangelo** [comment]
Not seeing this with Graph DB running properly
