### ISSUE TITLE
IndentationError in Cell 4.1

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#6]
During re-testing of current changes, I get the following after running Cell 4.1:
  File "<ipython-input-3-82166ca6301c>", line 46
    resp1 = requests.post(url=url1, data=json.dumps(data), headers=headers1)
    ^
IndentationError: unexpected indent

**Comment by Neha-Setia** [comment]
I am not able see this issue Scott, can you send me the screenshot for the same? 
And do let me know when will you be available to discuss this issue?

**Comment by scottdangelo** [comment]
I am actually blocked on issues with deploy-graph-db-container at the moment. I'll wait for a fix, and when I  get past the deploy-graph-db-container issue,  I'll retry the Notebook portion of this journey and see if this issue is still occurring.

**Comment by balajikadambi** [comment]
The Deploy Orient DB container is a pre-requisite(https://github.com/IBM/deploy-graph-db-container). The credentials for the Orient DB needs to be entered in the notebook.

**Comment by scottdangelo** [comment]
Not seeing this with Graph DB running properly
