### ISSUE TITLE
video should use thumbnail as link

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#7]
You can get a thumbnail image of your video here:
https://www.doctormckay.com/utilities/youtubethumbnail.php

Then put as a link in your README.md as done in this journey:
[![](http://img.youtube.com/vi/aWKi4f6gytc/0.jpg)](https://youtu.be/aWKi4f6gytc)

That uses this syntax:
```
[![](http://img.youtube.com/vi/aWKi4f6gytc/0.jpg)](https://youtu.be/aWKi4f6gytc)
```

**Comment by Neha-Setia** [comment]
I have updated the readme with the thumbnail.
Thanks!

![thumbnailforvideo](https://user-images.githubusercontent.com/22287665/31848608-c74f3016-b653-11e7-95c1-c2fc49649818.jpg)

**Comment by scottdangelo** [comment]
Looks good. Thanks.
