### ISSUE TITLE
step #5 instructions to run cells are out of order

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#8]
There are instructions in step 5 to run cells:
```
Run the cell below 3. Add your service credentials for Object Storage to load the variable credentials_1.

Run the cell below 4.1. Loading the config.json to load the configuration file
```

But we have never run the cells above.
This is confusing, and the instructions should just explain how to run each cell from top to bottom in Step 7

**Comment by Neha-Setia** [comment]
Please check the readme. I have updated this.

**Comment by scottdangelo** [comment]
Looks Good.
