### ISSUE TITLE
README needs instructions to add cluster IP and Port

### ISSUE THREAD

**Issue by scottdangelo** [IBM/graph-db-insights#9]
Readme should include explicit instructions to add K8s cluster IP and Port. This is already in the notebook, but in small print and easy to miss:
```
5. Connect to OrientDB
Uncomment the first line after entering the IP address of the Kubernetes cluster and the port.
```

**Comment by Neha-Setia** [comment]
Hey scott, 
The notebook makes use of the config file. I have given instructions in the readme to update the config file with IP address and the port. 
<img width="752" alt="screen shot 2017-10-21 at 11 31 44 am" src="https://user-images.githubusercontent.com/22287665/31848602-807042ac-b653-11e7-826e-72c9a67d435c.png">

**Comment by Neha-Setia** [comment]
Hey Scott, 
I agree that makes sense. I have included the details for the same. Attaching the screenshot!
<img width="751" alt="screen shot 2017-10-24 at 10 45 28 am" src="https://user-images.githubusercontent.com/22287665/31925774-8a47ed1e-b8a8-11e7-9ffa-9c23ef57331e.png">

**Comment by scottdangelo** [comment]
I think those details will be a big help.
One nit: You have these instructions first, in step 1. Then in step 3 you create the notebook. I think these instructions would be less confusing if you put them after creating the notebook. They could go in their own step.

**Comment by Neha-Setia** [comment]
Hey Scott,
I have added an additional step after the create notebook `additional notes for the notebook`
<img width="751" alt="screen shot 2017-10-25 at 11 00 54 am" src="https://user-images.githubusercontent.com/22287665/31982048-3f5ea028-b974-11e7-995f-3fe80efa4821.png">
